### ISSUE TITLE
Pagination - filtering games users 

### ISSUE THREAD

**Issue by CharlieMcFly** [RaphaelParment/ppio-web#2]

**Comment by CharlieMcFly** [comment]
get all users and get all matches

**Comment by jonbodart** [comment]
Pagination implemented.
Supported by adding query params : "limit" and "offset". If not provided default values 20 and 0 are taken. 
The response is a wrapper as following: 
{count: [MAX_AMOUNT_ROWS],
items: [items_returned]}

**Comment by jonbodart** [comment]
Filter also implemented:
See hereafter result : 
![image](https://user-images.githubusercontent.com/10274272/39409221-958347c2-4be3-11e8-9faa-6815aca4ba5b.png)

**Comment by jonbodart** [comment]
Filter and pagination also works for players:

![image](https://user-images.githubusercontent.com/10274272/39409489-28a8b45c-4be8-11e8-96c8-db8bd8c77c5e.png)

**Comment by CharlieMcFly** [comment]
I cannot get all the matches of a user .
I need something like : http://<ip>/player/:id/games -> to retrieve all the match of a user
